create table
  public.versions (
    id bigint generated by default as identity not null,
    acronym text not null,
    full_name text not null,
    language text not null,
    available boolean not null,
    constraint version_pkey primary key (id)
  ) tablespace pg_default;