create table
  public.highlights (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone null default now(),
    book bigint not null,
    chapter bigint not null,
    verse bigint not null,
    color text null,
    version_id bigint null,
    user_id uuid not null,
    constraint highlights_pkey primary key (id),
    constraint highlights_version_id_fkey foreign key (version_id) references versions (id) on delete set null,
    constraint highlights_user_id_fkey foreign key (user_id) references auth.users (id) on delete cascade
  ) tablespace pg_default;