create table
  public.bookmarks (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone null default now(),
    book bigint not null,
    chapter bigint not null,
    dynamic boolean null default true,
    user_id uuid null,
    color text null,
    title text null,
    constraint bookmarks_pkey primary key (id),
    constraint bookmarks_user_id_fkey foreign key (user_id) references auth.users (id) on delete cascade
  ) tablespace pg_default;